### PR TITLE
Webhook URLs should be https only

### PR DESCRIPTION
**Pull request by shifi**
Related to https://github.com/airbrake/airbrake-app/pull/3175.

### CODE REVIEW

**Comment by phumpal** [comment]
LGTM. I'd wait for another review though

It may be counterintuitive not knowing the reasoning behind this.

**Comment by shifi** [comment]
> It may be counterintuitive not knowing the reasoning behind this.

That's why I linked to airbrake/airbrake-app#3175 :P

**Comment by shifi** [comment]
@thompiler @mmcdaris ^

**Comment by kyrylo** [comment]
I think I don't understand what you are confused about. :)

**Comment by kyrylo** [comment]
> @phumpal 
> It may be counterintuitive not knowing the reasoning behind this.

Elaborate?

**Comment by thompiler** [comment]
LGTM 👍

**Pull request merged**
