### PR TITLE
Jira doc changes

### LINKED ISSUE #53: JIRA docs need update
[Testing your JIRA integration settings](https://airbrake.io/docs/integrations/jira/#testing-your-jira-integration-settings) section is outdated (screenshots are from old UI).

### PR DESCRIPTION
**Pull request by stuartmoore1023**
Updated images in jira doc. closes #53

### CODE REVIEW

**Comment by shifi** [comment]
@stuartmoore1023 @thompiler 
LGTM but let's please start to add screenshots without integration list on the left. That way we are only showing relevant info and we don't need to update the screenshot when we add new integration.

jira

I added new PT settings screenshot without that list in https://github.com/airbrake/airbrake-docs/pull/95/files.

**Comment by thompiler** [comment]
>LGTM but let's please start to add screenshots without integration list on the left. That way we are only showing relevant info and we don't need to update the screenshot when we add new integration.

Sounds good to me. @stuartmoore1023 let's switch out this [image](https://github.com/airbrake/airbrake-docs/blob/jira-doc-changes/jekyll/assets/img/docs/integrations/jira_settings.png) for one that doesn't have the integrations list as @shifi suggests.

**Comment by stuartmoore1023** [comment]
Made the change. Not sure if I need to do an actual pr as it looks like the correct image is not in.

**Comment by thompiler** [comment]
@stuartmoore1023 I see the correct image file with the integrations list removed when I check the "files changed" tab in this PR:
https://github.com/airbrake/airbrake-docs/blob/0ca9ed5659d4bad7e92d880f3842afedd62cfbe4/jekyll/assets/img/docs/integrations/jira_settings.png

You replaced it correctly.

**Comment by stuartmoore1023** [comment]
Good to go?

**Comment by thompiler** [comment]
This is good to squash and merge. 👍

**Pull request merged**
