### PR TITLE
Search and filtering update terms and image

### LINKED ISSUE #206: RE: /airbrake-faq/how-do-i-use-search-and-filtering
Replace "More aggregations" with "Custom aggregations" and add a new screenshot.

ma

### PR DESCRIPTION
**Pull request by stuartmoore1023**
Closes #206 

PTAL

### CODE REVIEW

**Comment by stuartmoore1023** [comment]
Made the image as large as I can without the buttons changing position. @sgray is there a way to increase the image size in the doc?

**Comment by sgray** [comment]
@stuartmoore1023 I think you need to take the screenshot on a HiDPI screen. I've got an image we can use. Do you mind if I push an update to this branch?

**Comment by stuartmoore1023** [comment]
Not at all @sgray. Thanks!

**Comment by sgray** [comment]
Thanks @stuartmoore1023, I think it looks good now. Merging.

**Pull request merged**
