### PR TITLE
Add section explaining the selective limiting

### PR DESCRIPTION
**Pull request by thompiler**
Explains new feature added to the way Airbrake collects errors from very large error groups

screen shot 2017-05-22 at 4 23 04 pm

### CODE REVIEW

**Comment by kyrylo** [comment]
Should `last_updated: May 11, 2016` be updated, too?

More general question: can we somehow automate this? It's a bit tedious to update it manually.

**Comment by thompiler** [comment]
>Should `last_updated: May 11, 2016` be updated, too?

Thanks. Good catch.
>More general question: can we somehow automate this? It's a bit tedious to update it manually.

Automation would be nice but, if possible, I'd rather just remove all the dates since they don't seem to be used anywhere in our docs unless I'm missing something. @mmcdaris do you know why these were included to begin with? They don't seem to be used.

**Comment by mmcdaris** [comment]
Let's remove the dates. The docs are in version control and that's history enough for me :)
We'd have to confirm that nothing breaks when they are removed but I don't think they serve a purpose.

**Comment by thompiler** [comment]
>Let's remove the dates. The docs are in version control and that's history enough for me :)
We'd have to confirm that nothing breaks when they are removed but I don't think they serve a purpose.

Sounds good. I made https://github.com/airbrake/airbrake-docs/pull/130 to remove them. I couldn't find anything that didn't work properly or look different after viewing essentially every doc.

**Comment by thompiler** [comment]
PTAL

**Comment by thompiler** [comment]
Thanks @sgray!

**Pull request merged**
