### PR TITLE
Add a Perfomance Monitoring doc for Flask

### PR DESCRIPTION
**Pull request by mmcdaris**
This doc provides information on how to get started with Performance Monitoring for Flask apps. The old links have been updated to point to the new doc.

<details>
<summary>Screenshot of Performance Monitoring for Flask apps doc</summary>

flask-perf
</details>

### CODE REVIEW

**Comment by thompiler** [comment]
Is it valuable to provide this information in this new doc? It seems to largely replicate the info in the [existing Flask doc](https://airbrake.io/docs/installing-airbrake/installing-airbrake-in-a-flask-app/). Maybe we could do one of these:
- Make this new doc a stub and link to the existing doc
- Make a "supported languages" section in the [Performance Monitoring FAQ](https://airbrake.io/docs/performance-monitoring/frequently-asked-questions/)
- Add a Performance Monitoring section to the existing Flask doc

**Comment by mmcdaris** [comment]
Thanks @thompiler! I like having these per language docs in the Performance Monitoring section for a few reasons. When you look at the [category](https://airbrake.io/docs/performance-monitoring/) you can easily see which languages support performance monitoring, the user may be more likely to discover other performance monitoring docs, and I like the option of giving more specific info to users who arrived to get started with Performance Monitoring.

> It seems to largely replicate the info in the [existing Flask doc](https://airbrake.io/docs/installing-airbrake/installing-airbrake-in-a-flask-app/).

Great point on the duplication, I'm going to extract the duplicated install instructions to it's own partial to DRY it out.

> Add a Performance Monitoring section to the existing Flask doc

👍 	This doc should be updated to mention the early access support for Performance Monitoring.

**Comment by thompiler** [comment]
Sounds good to me. 👍

**Comment by mmcdaris** [comment]
PTAL @thompiler, I've moved the install instructions for Flask to it's own partial and made mention of Performance Monitoring support in the Flask install doc.

**Pull request merged**
