### PR TITLE
Adds /docs path to s3_website config

### PR DESCRIPTION
**Pull request by phumpal**
If not specified it will default to the root path.

Part of https://github.com/airbrake/ansible/pull/1549

### CODE REVIEW

**Comment by phumpal** [comment]
Although I've pushed the web site

```
...
[succ] Created /docs/troubleshooting-2/index.html (max-age=86400 | text/html; charset=utf-8 | gzip | REDUCED_REDUNDANCY)
[succ] Created /docs/troubleshooting-2/notifier-troubleshooting/index.html (max-age=86400 | text/html; charset=utf-8 | gzip | REDUCED_REDUNDANCY)
[succ] Created /docs/troubleshooting-2/ssl-certificate-error/index.html (max-age=86400 | text/html; charset=utf-8 | gzip | REDUCED_REDUNDANCY)
[info] Summary: Created 226 files. Transferred 5.0 MB, 5.2 MB/s.
[info] Successfully pushed the website to http://airbrake-staging-docs-1.s3-website-us-east-1.amazonaws.com
```


s3 shows a directory without a name

Alt text

**Comment by phumpal** [comment]
Fixed.

**Comment by phumpal** [comment]
@mmcdaris PTAL

**Comment by mmcdaris** [comment]
Good catch, This makes sense to me and matches with the current setup for our [docs s3 buckets on development](https://s3.console.aws.amazon.com/s3/buckets/airbrake-docs-staging/?region=us-east-1&tab=overview)

screen shot 2017-09-19 at 3 03 31 pm

**Pull request closed without merging**
