### PR TITLE
Update heroku info

### PR DESCRIPTION
**Pull request by stuartmoore1023**
Update config info per #326  PTAL

### CODE REVIEW

**Comment by thompiler** [comment]
This section should use the names referenced in the screenshot right?

Screen Shot 2019-04-09 at 12 16 59 PM

**Comment by stuartmoore1023** [comment]
Wasn't sure since @shifi said they can be changed. I can change them if you think that's best.

**Comment by thompiler** [comment]
>Wasn't sure since @shifi said they can be changed. I can change them if you think that's best.

Yeah, I think we should use the default variable names otherwise, it seems like we're suggesting that people should rename them to get our example to work right?

Also, you can only change the variable **value**, not the name as far as I can see so I think that screenshot could be misleading.

**Comment by stuartmoore1023** [comment]
Changes per Thom.

**Pull request closed without merging**
